
import _Button from 'antd/es/button';
import _Affix from 'antd/es/affix';
// import _AutoComplete from 'antd/es/auto-complete';
// import _Avatar from 'antd/es/avatar';
import _BackTop from 'antd/es/back-top';
// import _Badge from 'antd/es/badge';
import _Breadcrumb from 'antd/es/breadcrumb';
// import _Calendar from 'antd/es/calendar';
// import _Card from 'antd/es/card';
// import _Collapse from 'antd/es/collapse';
// import _Carousel from 'antd/es/carousel';
// import _Cascader from 'antd/es/cascader';
// import _DatePicker from 'antd/es/date-picker';
// import _Divider from 'antd/es/divider';
import _Dropdown from 'antd/es/dropdown';
import _Icon from 'antd/es/icon';
import _Layout from 'antd/es/layout';
// import _List from 'antd/es/list';
// import _LocaleProvider from 'antd/es/locale-provider';
import _Menu from 'antd/es/menu';
import _Modal from 'antd/es/modal';
import _Spin from 'antd/es/spin';
// import _Steps from 'antd/es/steps';
// import _Transfer from 'antd/es/transfer';
// import _Tree from 'antd/es/tree';
// import _TreeSelect from 'antd/es/tree-select';
import _Tabs from 'antd/es/tabs';
// import _Tag from 'antd/es/tag';
// import _TimePicker from 'antd/es/time-picker';
// import _Timeline from 'antd/es/timeline';
// import _Mention from 'antd/es/mention';
// import _Upload from 'antd/es/upload';
// import _version from 'antd/es/version';
import _Tooltip from 'antd/es/tooltip';
import _Checkbox from 'antd/es/checkbox';
import _Switch from 'antd/es/switch';
import _InputNumber from 'antd/es/input-number';
import _Slider from 'antd/es/slider';

(function (that: any) {
    that.Affix = _Affix;
    that.Slider = _Slider;
    that.Switch = _Switch;
    that.InputNumber = _InputNumber;
    that.Tooltip = _Tooltip;
    that.Checkbox = _Checkbox;
    that.BackTop = _BackTop;
    that.Breadcrumb = _Breadcrumb;
    that.Dropdown = _Dropdown;
    that.Icon = _Icon;
    that.Layout = _Layout;
    that.Menu = _Menu;
    that.Spin = _Spin;
    that.Tabs = _Tabs;
    that.Button = _Button;
    that.Modal = _Modal;
     
})( (window as any).Antd || ( (window as any).Antd = {}));