
// import _Anchor from 'antd/es/anchor';
// import _Alert from 'antd/es/alert';
// import _Button from 'antd/es/button';
// import _Checkbox from 'antd/es/checkbox';
// import _Col from 'antd/es/col';
// import _Row from 'antd/es/row';
// import _Form from 'antd/es/form';
// import _Select from 'antd/es/select';
// import _Input from 'antd/es/input';
// import _notification from 'antd/es/notification';
// import _Pagination from 'antd/es/pagination';
// import _Radio from 'antd/es/radio';
// import _Slider from 'antd/es/slider';
// import _Switch from 'antd/es/switch';
// import _Tooltip from 'antd/es/tooltip';
// import _message from 'antd/es/message';
// import _Popconfirm from 'antd/es/popconfirm';
// import _Popover from 'antd/es/popover';
// import _Progress from 'antd/es/progress';
// import _Table from 'antd/es/table';

///////////////////////////////////////////////////

import _Affix from 'antd/es/affix';
// import _AutoComplete from 'antd/es/auto-complete';
// import _Avatar from 'antd/es/avatar';
import _BackTop from 'antd/es/back-top';
// import _Badge from 'antd/es/badge';
import _Breadcrumb from 'antd/es/breadcrumb';
// import _Calendar from 'antd/es/calendar';
// import _Card from 'antd/es/card';
// import _Collapse from 'antd/es/collapse';
// import _Carousel from 'antd/es/carousel';
// import _Cascader from 'antd/es/cascader';
// import _DatePicker from 'antd/es/date-picker';
// import _Divider from 'antd/es/divider';
import _Dropdown from 'antd/es/dropdown';
import _Icon from 'antd/es/icon';
import _Layout from 'antd/es/layout';
// import _List from 'antd/es/list';
// import _LocaleProvider from 'antd/es/locale-provider';
import _Menu from 'antd/es/menu';
// import _Modal from 'antd/es/modal';
import _Spin from 'antd/es/spin';
// import _Steps from 'antd/es/steps';
// import _Transfer from 'antd/es/transfer';
// import _Tree from 'antd/es/tree';
// import _TreeSelect from 'antd/es/tree-select';
import _Tabs from 'antd/es/tabs';
// import _Tag from 'antd/es/tag';
// import _TimePicker from 'antd/es/time-picker';
// import _Timeline from 'antd/es/timeline';
// import _Mention from 'antd/es/mention';
// import _Upload from 'antd/es/upload';
// import _version from 'antd/es/version';

(function (that: any) {
    that.Affix = _Affix;
    that.BackTop = _BackTop;
    that.Breadcrumb = _Breadcrumb;
    that.Dropdown = _Dropdown;
    that.Icon = _Icon;
    that.Layout = _Layout;
    that.Menu = _Menu;
    that.Spin = _Spin;
    that.Tabs = _Tabs;
    // that.Anchor = _Anchor;
    //    that.AutoComplete = _AutoComplete ;
    // that.Alert = _Alert;
    //    that.Avatar = _Avatar ;
    //    that.Badge = _Badge ;
    // that.Button = _Button;
    //    that.Calendar = _Calendar ;
    //    that.Card = _Card ;
    //    that.Collapse = _Collapse ;
    //    that.Carousel = _Carousel ;
    //    that.Cascader = _Cascader ;
    // that.Checkbox = _Checkbox;
    // that.Col = _Col;
    //    that.DatePicker = _DatePicker ;
    //    that.Divider = _Divider ;
    // that.Form = _Form;
    // that.Input = _Input;
    // that.InputNumber = _InputNumber;
    //    that.List= _List;
    //    that.LocaleProvider = _LocaleProvider ;
    // that.message = _message;
    //    that.Modal= _Modal;
    // that.notification = _notification;
    // that.Pagination = _Pagination;
    // that.Popconfirm = _Popconfirm;
    // that.Popover = _Popover;
    // that.Progress = _Progress;
    // that.Radio = _Radio;
    //    that.Rate = _Rate ;
    // that.Row = _Row;
    // that.Select = _Select;
    // that.Slider = _Slider;
    //    that.Steps = _Steps ;
    // that.Switch = _Switch;
    // that.Table = _Table;
    //    that.Transfer = _Transfer ;
    //    that.Tree = _Tree ;
    //    that.TreeSelect = _TreeSelect ;
    //    that.Tag = _Tag ;
    //    that.TimePicker = _TimePicker ;
    //    that.Timeline = _Timeline ;
    // that.Tooltip = _Tooltip;
    //     Mention = _Mention ;
    //    that.Upload = _Upload ;
    //    that.version = _version ;
})( (window as any).Antd || ( (window as any).Antd = {}));